//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisPeformans.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hedefler
    {
        public int HedefID { get; set; }
        public Nullable<int> HedefAdet { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> HedefAyID { get; set; }
        public Nullable<int> MagazaID { get; set; }
    }
}
