//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisPeformans.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HedefAylari
    {
        public int HedefAyID { get; set; }
        public string HedefAyi { get; set; }
        public Nullable<System.DateTime> HedefTarihiBaslangic { get; set; }
        public Nullable<System.DateTime> HedefTarihiBitis { get; set; }
    }
}
