//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisPeformans.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisDetaylari
    {
        public int SatisDetayID { get; set; }
        public Nullable<int> SatisID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> SatisAdeti { get; set; }
        public Nullable<int> SatisDurumID { get; set; }
        public Nullable<int> MagazaID { get; set; }
        public Nullable<int> HedefAyID { get; set; }
        public Nullable<int> IslemKanaliID { get; set; }
        public string MusteriAdiSoyadi { get; set; }
        public string MusteriNo { get; set; }
        public string MusteriTcNo { get; set; }
        public string IslemNo { get; set; }
        public string Tarife { get; set; }
        public string Kimlik { get; set; }
        public string Bundle { get; set; }
        public string Aciklama { get; set; }
    }
}
